import React,{useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,ArrowDownRight,ArrowUpRight,Check,ChevronDown,CloudOff,Compass,Database,Info,Plane,RotateCcw,Shield,Ship,SlidersHorizontal,Wifi,Wind,Zap} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import MissionGlobe from './Globe';
import {simulate,Action,Forecast} from './simulation';
import {DEFAULT_ACTION,DEFAULT_SCENARIO_NAME,PersistedScenarioState,restoreScenarioState,persistScenarioState,readActionLog,isPersistedScenarioState} from './scenarioState';
type Log={time:string,text:string};
const nav=[['Mission Control',Compass],['Logistics',Ship],['Inventory',Database],['Scenarios',SlidersHorizontal],['Activity Log',Activity]] as const;
const arrivalDate=(day:number)=>new Date(Date.now()+day*86400000).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
function App(){
 const [scenarioState,setScenarioState]=useState<PersistedScenarioState>(()=>restoreScenarioState());
 const {delayDays:delay,action:applied,scenarioName:scenario}=scenarioState.current;
 const selection:Action=scenarioState.selectedAction;const offline=scenarioState.executionMode==='offline-demo';
 const [connected,setConnected]=useState(()=>typeof navigator==='undefined'||navigator.onLine);const [page,setPage]=useState('Mission Control');const [log,setLog]=useState<Log[]>(()=>readActionLog());const [notice,setNotice]=useState('');
 const forecast=useMemo(()=>simulate(delay,applied),[delay,applied]);const baseline=useMemo(()=>simulate(delay),[delay]);const impact=useMemo(()=>selection?simulate(delay,selection):baseline,[delay,selection,baseline]);
 const recommendation=useMemo(()=>{const a=simulate(delay,{type:'airlift',amount:20000}),d=simulate(delay,{type:'demand',amount:20});return a.probability<d.probability||a.probability===d.probability&&a.runway>=d.runway?'20,000 L hypothetical airlift':'20% hypothetical demand reduction'},[delay]);
 const sortedRunouts=forecast.runout.slice().sort((a,b)=>a-b);const runoutDates=sortedRunouts.length?[arrivalDate(sortedRunouts[0]),arrivalDate(sortedRunouts[Math.floor(sortedRunouts.length/2)]),arrivalDate(sortedRunouts[sortedRunouts.length-1])]:null;
 function commitScenarioState(next:PersistedScenarioState){persistScenarioState(next);setScenarioState(next)}
 function commitLog(next:Log[]){setLog(next);try{localStorage.setItem('setu-log',JSON.stringify(next))}catch{/* The simulation remains usable if local storage is unavailable. */}}
 useEffect(()=>{const item={id:'local-demo',scenarioState,delayDays:delay,scenario,applied,log,updatedAt:new Date().toISOString()};try{localStorage.setItem('setu-pending-sync',JSON.stringify(item));const queue:typeof item[]=JSON.parse(localStorage.getItem('setu-sync-queue')||'[]');const at=queue.findIndex(x=>x.id===item.id);if(at>=0)queue[at]=item;else queue.push(item);localStorage.setItem('setu-sync-queue',JSON.stringify(queue.slice(-20)))}catch{/* Keep local scenario behavior independent of the sync outbox. */}},[scenarioState,delay,scenario,applied,log]);
 async function reconcile(force=false,mode:PersistedScenarioState['executionMode']=scenarioState.executionMode){if(mode==='offline-demo'||(!connected&&!force))return;let queue:{id:string;scenarioState?:unknown;delayDays:number;scenario:string;applied:Action;log:Log[];updatedAt:string}[]=[];try{queue=JSON.parse(localStorage.getItem('setu-sync-queue')||'[]')}catch{return}const local=queue[queue.length-1];if(!local)return;const base=(import.meta.env.VITE_API_URL||'http://localhost:8000').replace(/\/$/,'');try{const response=await fetch(`${base}/api/scenarios`);if(!response.ok)return;const list=await response.json();const remote=list.find((x:any)=>x.id===local.id);const remoteTime=remote?.config?.updatedAt||remote?.updated_at||'';if(remote&&remoteTime>local.updatedAt){const config=remote.config;const remoteState=isPersistedScenarioState(config?.scenarioState)?(config.scenarioState.current.action?{...config.scenarioState,selectedAction:config.scenarioState.current.action}:config.scenarioState):{version:3,executionMode:'local-online',selectedAction:config?.applied??{...DEFAULT_ACTION},current:{stationId:'maitri',delayDays:config?.delayDays??0,scenarioName:config?.scenario||DEFAULT_SCENARIO_NAME,action:config?.applied??null},previous:null} as PersistedScenarioState;commitScenarioState(remoteState);commitLog(Array.isArray(config?.log)?config.log:[])}else{const saved=await fetch(`${base}/api/scenarios`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:local.id,name:local.scenario,config:local})});if(!saved.ok)return}localStorage.setItem('setu-sync-queue','[]')}catch{/* retain pending local changes for the next reconnect */}}
 useEffect(()=>{if(!offline&&'serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})},[offline]);
 useEffect(()=>{const on=()=>{setConnected(true);if(!offline)void reconcile(true,'local-online')};const off=()=>setConnected(false);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off)}},[offline,connected,delay,scenario,applied,log]);
 function chooseAction(next:Exclude<Action,null>){commitScenarioState({...scenarioState,selectedAction:next})}
 function chooseDelay(d:number){commitScenarioState({...scenarioState,current:{...scenarioState.current,delayDays:d,action:null},previous:null})}
 function apply(){if(!selection)return;const previous=scenarioState.current;commitScenarioState({...scenarioState,current:{...previous,action:selection},previous});const label=selection.type==='airlift'?`Hypothetical airlift of ${selection.amount.toLocaleString()} L`:`Hypothetical ${selection.amount}% demand reduction`;commitLog([{time:new Date().toLocaleString(),text:label},...log]);setNotice('Hypothetical action applied to simulation — real-world authorization and execution are not performed.');setTimeout(()=>setNotice(''),6500)}
 function undo(){const previous=scenarioState.previous??{stationId:'maitri' as const,delayDays:0,scenarioName:DEFAULT_SCENARIO_NAME,action:null};const restored={...scenarioState,current:previous,previous:null,selectedAction:previous.action??{...DEFAULT_ACTION}};commitScenarioState(restored);commitLog([{time:new Date().toLocaleString(),text:'Undid active hypothetical action; restored previous scenario.'},...log]);setNotice('Previous scenario restored.');setTimeout(()=>setNotice(''),3000)}
 function reset(){const baseline:PersistedScenarioState={...scenarioState,version:3,current:{stationId:'maitri',delayDays:0,scenarioName:DEFAULT_SCENARIO_NAME,action:null},previous:null,selectedAction:{...DEFAULT_ACTION}};commitScenarioState(baseline);setNotice('Scenario reset to baseline.');setTimeout(()=>setNotice(''),3000)}
 const gauge=forecast.probability*100;const severity=forecast.risk.toLowerCase();
 return <div className="app-shell">
  <aside className="rail"><div className="brand-mark">S<span>↗</span></div><div className="brand-name">SETU<small>POLAR OPERATIONS</small></div><div className="rail-rule"/>{nav.map(([label,Icon])=><button key={label} className={`nav-item ${page===label?'active':''}`} onClick={()=>setPage(label)}><Icon size={17}/><span>{label}</span></button>)}<div className="rail-bottom"><div className="rail-orbit">◉</div><span>SIH 26062</span><small>PROTOTYPE · v0.1</small></div></aside>
  <main className="main-area"><header className="topbar"><div className="crumb"><span>OPERATIONS</span><b>/</b>{page.toUpperCase()}</div><div className="top-controls"><div className="mode-pill"><i/> SIMULATION MODE</div><button className={`network ${offline||!connected?'is-offline':''}`} onClick={()=>{const executionMode=offline?'local-online':'offline-demo';commitScenarioState({...scenarioState,executionMode});if(executionMode==='local-online')void reconcile(true,'local-online')}}>{offline||!connected?<CloudOff size={14}/>:<Wifi size={14}/>} {offline?'OFFLINE DEMO':!connected?'BROWSER OFFLINE':'LOCAL · ONLINE'}</button><button className="scenario-select" onClick={()=>commitScenarioState({...scenarioState,current:{...scenarioState.current,scenarioName:scenario==='Summer Resupply 26/27'?'Maitri Resupply Alpha':'Summer Resupply 26/27'}})}><span className="tiny-square"/>{scenario}<ChevronDown size={13}/></button></div></header>
  {page==='Mission Control'?<><section className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> ANTARCTIC EXPEDITION · 2026–27</div><h1>Mission Control</h1><p>Model the impact of resupply delays on station fuel readiness.</p></div><button className="reset-btn" onClick={reset}><RotateCcw size={14}/> RESET SCENARIO</button></section>
   <section className="control-strip"><div className="control-title"><div className="control-icon"><Ship size={18}/></div><div><strong>Resupply vessel delay</strong><small>Adjust the inbound ship's schedule</small></div></div><div className="delay-slider"><div className="range-label"><span>0 days</span><span className="delay-current">{delay}<small> DAYS</small></span><span>30 days</span></div><input aria-label="Ship delay days" type="range" min="0" max="30" value={delay} onChange={e=>chooseDelay(+e.target.value)} style={{'--progress':`${delay/30*100}%`} as React.CSSProperties}/><div className="range-ticks">{[0,5,10,15,20,25,30].map(x=><button key={x} onClick={()=>chooseDelay(x)} className={delay===x?'tick-selected':''}>{x}</button>)}</div></div><div className="arrival-block"><small>PROJECTED ARRIVAL</small><b>{arrivalDate(forecast.arrival)}</b><span className="arrival-change">{delay===0?'ON SCHEDULE':`+${delay} DAYS FROM PLAN`}</span></div></section>
   <div className="dashboard-grid"><section className="panel map-panel"><div className="panel-heading"><div><span className="section-kicker">ROUTE OVERVIEW</span><h2>Southern Ocean transit</h2></div><div className="live-chip"><i/> SIMULATED LIVE</div></div><MissionGlobe forecast={forecast} delay={delay}/><div className="map-legend"><span><i className="legend-vessel"/> RESUPPLY VESSEL</span><span><i className="legend-station"/> RESEARCH STATION</span><span><i className="legend-route"/> PLANNED ROUTE</span><span className="map-zoom">DRAG TO ROTATE · SCROLL TO ZOOM</span></div></section>
    <aside className="panel risk-panel"><div className="panel-heading"><div><span className="section-kicker">MAITRI · FUEL READINESS</span><h2>Shortfall risk</h2></div><span className={`risk-badge ${severity}`}><i/>{forecast.risk}</span></div><div className="risk-number"><strong>{gauge.toFixed(1)}<small>%</small></strong><span>chance of stockout<br/>before resupply</span></div><div className="risk-meter"><div className={`meter-fill ${severity}`} style={{width:`${Math.max(3,gauge)}%`}}/></div><div className="risk-stats"><div><small>FUEL RUNWAY</small><strong>{forecast.runway.toFixed(0)} <em>days</em></strong></div><div><small>RESERVE BREACH</small><strong>{(forecast.reserveProbability*100).toFixed(1)} <em>%</em></strong></div></div><div className="why-box"><div className="why-title"><Info size={14}/> WHY IS THIS STATION AT RISK?</div><p>{delay>0?`A ${delay}-day transit delay shifts the expected delivery to day ${forecast.arrival}. `:'The scheduled shipment is expected on day 65. '}{baseline.probability>0?`${(baseline.probability*100).toFixed(1)}% of ${1000} sampled demand, arrival, and delivery outcomes result in stockout before the delivery.`:'Under current assumptions, sampled demand, arrival, and delivery variation produced no stockouts before delivery.'} The estimate uses synthetic inventory and consumption assumptions.</p></div><div className="simulation-tag"><Shield size={13}/> {applied?'ACTION SCENARIO':'1,000 MONTE CARLO TRIALS'} <span>· SEED 26062</span></div></aside>
    <section className="panel forecast-panel"><div className="panel-heading"><div><span className="section-kicker">FUEL INVENTORY · LITERS</span><h2>Projected fuel reserve</h2></div><div className="chart-legend"><span><i/> P10–P90 RANGE</span><span><i/> MEDIAN</span><span><i/> SAFETY RESERVE</span></div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={forecast.series} margin={{top:10,right:8,left:0,bottom:0}}><defs><linearGradient id="rangeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#54c9dd" stopOpacity={.24}/><stop offset="100%" stopColor="#54c9dd" stopOpacity={.025}/></linearGradient></defs><CartesianGrid stroke="#1b303a" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="day" tick={{fill:'#77909b',fontSize:10}} tickLine={false} axisLine={false} ticks={[0,30,60,90,120,150,180]} tickFormatter={x=>`D${x}`}/><YAxis tick={{fill:'#77909b',fontSize:10}} tickLine={false} axisLine={false} width={48} tickFormatter={x=>x>=1000?`${(x/1000).toFixed(0)}k`:x}/><Tooltip contentStyle={{background:'#0c1b24',border:'1px solid #26404c',borderRadius:8,color:'#e3f4f7'}} labelFormatter={x=>`Day ${x}`} formatter={(v:any,n:any)=>[`${Number(v).toLocaleString()} L`,n==='median'?'Median fuel':n==='band'?'P90–P10 band':'P10 baseline']}/><Area dataKey="p10" stackId="range" stroke="none" fill="transparent" isAnimationActive={false}/><Area dataKey="band" stackId="range" stroke="none" fill="url(#rangeFill)" isAnimationActive={false}/><Area dataKey="median" stroke="#64d8e6" strokeWidth={2} fill="none" dot={false}/><ReferenceLine y={45000} stroke="#efa950" strokeDasharray="5 5" label={{value:'SAFETY RESERVE',fill:'#efa950',fontSize:9,position:'insideTopRight'}}/><ReferenceLine x={forecast.arrival} stroke="#d4eff4" strokeDasharray="4 4" label={{value:'SHIP ARRIVAL',fill:'#d4eff4',fontSize:9,position:'insideTopLeft'}}/><ReferenceLine x={120} stroke="#916db5" strokeDasharray="3 5" label={{value:'ISOLATION PERIOD END*',fill:'#af94c8',fontSize:9,position:'insideTopRight'}}/></AreaChart></ResponsiveContainer></div><div className="chart-foot"><span><i className="dot-cyan"/> P10–P90 daily inventory range · 1,000 trials</span><span>{runoutDates?`STOCKOUT · ${runoutDates[0]} / MEDIAN ${runoutDates[1]} / ${runoutDates[2]}`:`NO STOCKOUT IN SIMULATION HORIZON`} · * Illustrative marker</span></div></section>
    <section className="panel action-panel"><div className="panel-heading"><div><span className="section-kicker">DECISION SUPPORT</span><h2>Test a corrective action</h2></div><span className="hypothetical-label">HYPOTHETICAL</span></div><div className="recommendation-note"><Zap size={12}/><span>RULE ENGINE SUGGESTS</span><b>{recommendation}</b><small>Lowest modeled shortfall risk; ties use longer fuel runway.</small></div><div className="action-tabs"><button className={selection?.type==='airlift'?'selected':''} onClick={()=>chooseAction({type:'airlift',amount:selection?.type==='airlift'?selection.amount:10000})}><Plane size={15}/> EMERGENCY AIRLIFT</button><button className={selection?.type==='demand'?'selected':''} onClick={()=>chooseAction({type:'demand',amount:selection?.type==='demand'?selection.amount:15})}><Wind size={15}/> DEMAND REDUCTION</button></div>{selection?.type==='airlift'?<div className="action-input"><div><label>ASSUMED FUEL QUANTITY</label><strong>{selection.amount.toLocaleString()} <small>L</small></strong></div><input aria-label="Hypothetical airlift fuel quantity" type="range" min="0" max="20000" step="1000" value={selection.amount} onChange={e=>chooseAction({type:'airlift',amount:+e.target.value})}/><small>SIMULATED PAYLOAD CAP ≤ 20,000 L</small></div>:<div className="action-input"><div><label>ASSUMED DEMAND REDUCTION</label><strong>{selection?.amount}<small>%</small></strong></div><input aria-label="Hypothetical demand reduction" type="range" min="0" max="40" step="5" value={selection?.amount||0} onChange={e=>chooseAction({type:'demand',amount:+e.target.value})}/><small>SYNTHETIC REDUCTION ASSUMPTION · 0–40%</small></div>}<div className="impact-row"><div><small>SHORTFALL PROBABILITY</small><div><b>{(baseline.probability*100).toFixed(1)}%</b><ArrowDownRight size={14}/><b className="positive">{(impact.probability*100).toFixed(1)}%</b></div></div><div><small>MEDIAN FUEL RUNWAY</small><div><b>{baseline.runway.toFixed(0)}d</b><ArrowUpRight size={14}/><b className="positive">{impact.runway.toFixed(0)}d</b></div></div></div><button className="apply-btn" onClick={apply}><Zap size={15}/> APPLY TO SIMULATION <span>→</span></button><div className="action-disclaimer">This is a scenario test only. Availability and operational approval are not verified.</div></section>
   </div><div className="bottom-grid"><section className="panel assumptions-panel"><div className="bottom-title"><Info size={15}/><b>MODEL ASSUMPTIONS</b><span>SYNTHETIC DEMO DATA</span></div><div className="assumption-list"><span>Initial stock <b>180,000 L</b></span><span>Mean daily use <b>1,850 L/day</b></span><span>Shipment <b>100,000 L</b></span><span>Planned arrival <b>Day 65</b></span><span>Safety reserve <b>45,000 L</b></span><span>Horizon <b>180 days</b></span></div></section><section className="panel action-result"><div className="bottom-title"><Activity size={15}/><b>SCENARIO STATUS</b></div><p>{applied?<><Check size={13}/> Hypothetical action active · {applied.type==='airlift'?`+${applied.amount.toLocaleString()} L airlift`:`${applied.amount}% demand reduction`}</>:'Baseline scenario · no hypothetical action applied'}</p>{applied&&<button className="undo-btn" onClick={undo}><RotateCcw size={11}/> UNDO ACTION</button>}<span>Results are computed locally from a reproducible 1,000-trial model.</span></section></div>
   <footer className="footer"><span>SETU · SIH26062 <b>·</b> Student prototype</span><span><AlertTriangle size={12}/> SYNTHETIC DEMO DATA · NOT AN OFFICIAL NCPOR SYSTEM</span><button onClick={()=>setPage('Sources')}>DATA SOURCES & ASSUMPTIONS</button></footer>
  </>:<GenericPage page={page} setPage={setPage} log={log} forecast={forecast} chooseDelay={chooseDelay} />}</main>{notice&&<div className="toast"><Check size={15}/>{notice}</div>}</div>
}
function GenericPage({page,setPage,log,forecast,chooseDelay}:{page:string,setPage:(s:string)=>void,log:Log[],forecast:Forecast,chooseDelay:(d:number)=>void}){return <div className="generic-page"><div className="eyebrow"><span className="eyebrow-line"/> SETU · POLAR OPERATIONS</div><h1>{page}</h1>{page==='Sources'?<section className="panel generic-panel"><h2>Data sources & assumptions</h2><p><b>SYNTHETIC DEMO DATA:</b> all fuel inventories, daily consumption, delivery quantities, vessel schedules, capacity limits, and uncertainty distributions are fictional configurable prototype assumptions. No live vessel, station, weather, flight, or inventory feeds are connected.</p><p>Public station coordinates used for map placement: Maitri (-70.7693, 11.7363) and Bharati (-69.4128, 76.1874), Antarctic facilities dataset by COMNAP: <a href="https://www.comnap.aq/antarctic-facilities-information/" target="_blank" rel="noreferrer">comnap.aq/antarctic-facilities-information</a>. Mumbai origin point is a public geographic reference coordinate.</p><p>All actions are hypothetical and do not establish availability, feasibility, approval, or execution. Production use would require NCPOR-authorized validated logistics, station inventory, and operational data integrations. Random seed 26062; 1,000 trials; normal demand deviation 12%, arrival deviation 4 days, shipment quantity deviation 5%.</p><button className="reset-btn" onClick={()=>setPage('Mission Control')}>RETURN TO MISSION CONTROL</button></section>:page==='Activity Log'?<section className="panel generic-panel"><h2>Applied scenario actions</h2>{log.length?log.map((x,i)=><div className="log-entry" key={i}><Activity size={15}/><span>{x.text}</span><small>{x.time}</small></div>):<p>No actions applied yet. Test a hypothetical action in Mission Control to create an audit entry.</p>}</section>:<section className="panel generic-panel"><div className="section-kicker">LOCAL SIMULATION WORKSPACE</div><h2>{page==='Logistics'?'Inbound resupply transit':page==='Inventory'?'Maitri fuel inventory':'Scenario presets'}</h2><p>{page==='Logistics'?`Synthetic vessel arrival in ${forecast.arrival} days. Delay, transit route, and projected fuel impact are controlled from Mission Control.`:page==='Inventory'?`Projected initial inventory: 180,000 liters · daily consumption assumption: 1,850 liters · ${forecast.runway.toFixed(0)} days of baseline fuel runway.`:'Select a delay preset to run it through the same local simulation model.'}</p>{page==='Scenarios'&&<div className="preset-row">{[0,7,15,30].map(d=><button key={d} className="preset-card" onClick={()=>{chooseDelay(d);setPage('Mission Control')}}><b>{d===0?'ON TIME':`${d}-DAY DELAY`}</b><small>Load into simulator →</small></button>)}</div>}<button className="reset-btn" onClick={()=>setPage('Mission Control')}>OPEN MISSION CONTROL</button></section>}</div>}
export default App;
