import {useEffect, useRef, useState} from 'react';
import Globe from 'react-globe.gl';
import {Forecast} from './simulation';
const stations=[{name:'MAITRI',lat:-70.7644,lng:11.7342},{name:'BHARATI',lat:-69.40683,lng:76.19533}];
const origin={name:'MUMBAI',lat:19.076,lng:72.8777};
export default function MissionGlobe({forecast,delay}:{forecast:Forecast,delay:number}){
 const ref=useRef<any>(null);const [width,setWidth]=useState(800);const [failed,setFailed]=useState(false);
 useEffect(()=>{const resize=()=>setWidth(Math.max(320,document.querySelector('.globe-wrap')?.clientWidth||800));resize();window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize)},[]);
 useEffect(()=>{const g=ref.current;if(g){g.pointOfView({lat:-70,lng:35,altitude:1.65},1000);g.controls().autoRotate=true;g.controls().autoRotateSpeed=.25}const timer=setTimeout(()=>{const c=document.querySelector('.globe-wrap canvas');if(!c)setFailed(true)},8000);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{const probe=new Image();probe.onload=()=>setFailed(false);probe.onerror=()=>setFailed(true);probe.src='https://unpkg.com/three-globe/example/img/earth-night.jpg';return()=>{probe.onload=null;probe.onerror=null}},[]);
 const route=[{lat:origin.lat,lng:origin.lng},{lat:-25,lng:62},{lat:-48,lng:48},{lat:-68,lng:35}];
 const dots=[...stations.map(s=>({...s,color:s.name==='MAITRI'?(forecast.risk==='CRITICAL'?'#fb7185':forecast.risk==='ELEVATED'?'#fbbf24':'#6ce7a2'):'#6ce7a2'})),origin];
 const delayProgress=Math.max(.08,Math.min(.9,.77-delay/38));const ship=()=>{const i=delayProgress*(route.length-1),idx=Math.floor(i),f=i-idx,a=route[idx],b=route[Math.min(idx+1,route.length-1)];return{lat:a.lat+(b.lat-a.lat)*f,lng:a.lng+(b.lng-a.lng)*f}};
 return <div className="globe-wrap">{!failed?<Globe ref={ref} width={width} height={440} globeImageUrl="https://unpkg.com/three-globe/example/img/earth-night.jpg" backgroundColor="rgba(0,0,0,0)" showAtmosphere atmosphereColor="#51b9d7" atmosphereAltitude={.18} pointsData={dots} pointLat="lat" pointLng="lng" pointColor="color" pointAltitude={(d:any)=>d.name==='MUMBAI'?.008:.025} pointRadius={(d:any)=>d.name==='MUMBAI'?.4:.65} pointLabel={(d:any)=>d.name==='MAITRI'?`Maitri · ${forecast.runway.toFixed(0)} synthetic fuel days · ${forecast.risk}`:d.name==='BHARATI'?'Bharati · reference station; fuel inventory not modeled in this demo':'Mumbai · simulated route origin'} labelsData={dots} labelLat="lat" labelLng="lng" labelText="name" labelSize={(d:any)=>d.name==='MUMBAI'?.55:.8} labelDotRadius={.25} labelColor={()=>'#d9f5ff'} labelResolution={2} arcsData={[{startLat:origin.lat,startLng:origin.lng,endLat:-70,endLng:35}]} arcColor={()=>['#52d9ed','#52d9ed']} arcStroke={.35} arcAltitudeAutoScale={.34} arcDashLength={.6} arcDashGap={.3} arcDashAnimateTime={2800} htmlElementsData={[{...ship(),name:'ship'}]} htmlLat="lat" htmlLng="lng" htmlElement={()=>{const el=document.createElement('div');el.innerHTML='✦';el.style.cssText='color:#71e8f7;font-size:22px;text-shadow:0 0 14px #71e8f7';return el}} onGlobeReady={()=>{}} onGlobeClick={()=>{}} onPointClick={()=>{}} />:<div className="globe-fallback"><div className="fallback-earth"><span>ANTARCTICA</span><i>✦</i></div><p>Interactive globe texture unavailable. Simulation controls and forecasts remain active.</p></div>}
 <div className="globe-vignette"/><div className="map-tag origin-tag"><b>MB</b> MUMBAI <small>ORIGIN</small></div><div className="map-tag station-tag"><b className="pulse"/> MAITRI <small>{forecast.risk}</small></div><div className="map-tag station-tag station-b"><b className="pulse"/> BHARATI <small>STATION</small></div><div className="globe-coordinates">70°46′S · 11°44′E &nbsp; / &nbsp; SOUTHERN OCEAN</div></div>
}
